db.jokes.insert({Joke : "'I am sorry' and 'I apologize' mean the same thing except when you're at a funeral", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "I intend to live forever, or die trying", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "We never knew he was a drunk until he showed up to work sober", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "A clear conscience is usually the sign of a bad memory", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "A blind man walks into a bar..And a table, and a chair.", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "At what age is it appropriate to tell my dog that he's adopted? ", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "Want to hear a pizza joke?. nah, it's too cheesy.", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "I used to be in a band, we were called 'lost dog'. You probably saw our posters. ", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "I childproofed the house but they still get in!", reference :"http://www.greatcleanjokes.com/jokes/sms-jokes/one-liners/",created : Date.now()})
db.jokes.insert({joke : "A computer once beat me at chess, but it was no match for me at kick boxing.", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "A day without sunshine is like, night.", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "Born free, taxed to death", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "For Sale: Parachute. Only used once, never opened", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "A bank is a place that will lend you money, if you can prove that you don't need it.", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "LAW OF MECHANICAL REPAIR: After your hands become coated with grease, your nose will begin to itch", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "What is faster Hot or cold? Hot, because you can catch a cold", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "When everything's coming your way, you're in the wrong lane", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})
db.jokes.insert({joke : "Time is what keeps things from happening all at once", reference :"http://www.tensionnot.com/jokes/one_liner_jokes",created : Date.now()})